# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Clustering'
  link: '/pages_you_can_read/clustering/clustering'
- label: Usage
  items:
    - label: 'anova'
      link: '/pages_you_can_read/anova/anova'
