defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        - title: "ANOVA"
          url: pages_you_can_read/anova/
          output: "web"
        - title: "ANOVA2"
          url: pages_you_can_read/anova/anova.md
          output: "web"
        
